'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
var _1 = require('.');
_1.User.hasOne(_1.Basket);
_1.Basket.belongsTo(_1.User);
_1.User.hasMany(_1.Rating);
_1.Rating.belongsTo(_1.User);
_1.Basket.hasMany(_1.BasketProduct);
_1.BasketProduct.belongsTo(_1.Basket);
_1.Type.hasMany(_1.Product);
_1.Product.belongsTo(_1.Type);
_1.Exporter.hasMany(_1.Product);
_1.Product.belongsTo(_1.Exporter);
_1.Product.hasMany(_1.Rating);
_1.Rating.belongsTo(_1.Product);
_1.Product.hasMany(_1.BasketProduct);
_1.BasketProduct.belongsTo(_1.Product);
_1.Product.hasMany(_1.ProductInfo, { as: 'info' });
_1.ProductInfo.belongsTo(_1.Product);
_1.Type.belongsToMany(_1.Exporter, { through: _1.TypeProduct });
_1.Exporter.belongsToMany(_1.Type, { through: _1.TypeProduct });
